# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marketplace_pb2 as marketplace__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marketplace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrontendServiceStub(object):
    """---- services ----

    client facing api - service pods implement this
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/marketplace.FrontendService/CreateItem',
                request_serializer=marketplace__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.FrontendService/GetItem',
                request_serializer=marketplace__pb2.GetItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.FrontendService/SearchItems',
                request_serializer=marketplace__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=marketplace__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.UpdateItem = channel.unary_unary(
                '/marketplace.FrontendService/UpdateItem',
                request_serializer=marketplace__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.UpdateItemResponse.FromString,
                _registered_method=True)
        self.PlaceBid = channel.unary_unary(
                '/marketplace.FrontendService/PlaceBid',
                request_serializer=marketplace__pb2.PlaceBidRequest.SerializeToString,
                response_deserializer=marketplace__pb2.PlaceBidResponse.FromString,
                _registered_method=True)
        self.JoinAuction = channel.unary_stream(
                '/marketplace.FrontendService/JoinAuction',
                request_serializer=marketplace__pb2.JoinAuctionRequest.SerializeToString,
                response_deserializer=marketplace__pb2.AuctionUpdate.FromString,
                _registered_method=True)


class FrontendServiceServicer(object):
    """---- services ----

    client facing api - service pods implement this
    """

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinAuction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=marketplace__pb2.CreateItemRequest.FromString,
                    response_serializer=marketplace__pb2.CreateItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=marketplace__pb2.GetItemRequest.FromString,
                    response_serializer=marketplace__pb2.GetItemResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=marketplace__pb2.SearchItemsRequest.FromString,
                    response_serializer=marketplace__pb2.SearchItemsResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=marketplace__pb2.UpdateItemRequest.FromString,
                    response_serializer=marketplace__pb2.UpdateItemResponse.SerializeToString,
            ),
            'PlaceBid': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBid,
                    request_deserializer=marketplace__pb2.PlaceBidRequest.FromString,
                    response_serializer=marketplace__pb2.PlaceBidResponse.SerializeToString,
            ),
            'JoinAuction': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinAuction,
                    request_deserializer=marketplace__pb2.JoinAuctionRequest.FromString,
                    response_serializer=marketplace__pb2.AuctionUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.FrontendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.FrontendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrontendService(object):
    """---- services ----

    client facing api - service pods implement this
    """

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.FrontendService/CreateItem',
            marketplace__pb2.CreateItemRequest.SerializeToString,
            marketplace__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.FrontendService/GetItem',
            marketplace__pb2.GetItemRequest.SerializeToString,
            marketplace__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.FrontendService/SearchItems',
            marketplace__pb2.SearchItemsRequest.SerializeToString,
            marketplace__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.FrontendService/UpdateItem',
            marketplace__pb2.UpdateItemRequest.SerializeToString,
            marketplace__pb2.UpdateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.FrontendService/PlaceBid',
            marketplace__pb2.PlaceBidRequest.SerializeToString,
            marketplace__pb2.PlaceBidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinAuction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/marketplace.FrontendService/JoinAuction',
            marketplace__pb2.JoinAuctionRequest.SerializeToString,
            marketplace__pb2.AuctionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StorageServiceStub(object):
    """storage api - all replicas expose this, they're all peers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Write = channel.unary_unary(
                '/marketplace.StorageService/Write',
                request_serializer=marketplace__pb2.StorageWriteRequest.SerializeToString,
                response_deserializer=marketplace__pb2.StorageWriteResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/marketplace.StorageService/Read',
                request_serializer=marketplace__pb2.StorageReadRequest.SerializeToString,
                response_deserializer=marketplace__pb2.StorageReadResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/marketplace.StorageService/Search',
                request_serializer=marketplace__pb2.StorageSearchRequest.SerializeToString,
                response_deserializer=marketplace__pb2.StorageSearchResponse.FromString,
                _registered_method=True)
        self.Repair = channel.unary_unary(
                '/marketplace.StorageService/Repair',
                request_serializer=marketplace__pb2.RepairRequest.SerializeToString,
                response_deserializer=marketplace__pb2.RepairResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/marketplace.StorageService/SyncState',
                request_serializer=marketplace__pb2.SyncRequest.SerializeToString,
                response_deserializer=marketplace__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/marketplace.StorageService/CheckHealth',
                request_serializer=marketplace__pb2.ReplicaHeartbeatRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ReplicaHeartbeatResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """storage api - all replicas expose this, they're all peers
    """

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Repair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=marketplace__pb2.StorageWriteRequest.FromString,
                    response_serializer=marketplace__pb2.StorageWriteResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=marketplace__pb2.StorageReadRequest.FromString,
                    response_serializer=marketplace__pb2.StorageReadResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=marketplace__pb2.StorageSearchRequest.FromString,
                    response_serializer=marketplace__pb2.StorageSearchResponse.SerializeToString,
            ),
            'Repair': grpc.unary_unary_rpc_method_handler(
                    servicer.Repair,
                    request_deserializer=marketplace__pb2.RepairRequest.FromString,
                    response_serializer=marketplace__pb2.RepairResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=marketplace__pb2.SyncRequest.FromString,
                    response_serializer=marketplace__pb2.SyncResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=marketplace__pb2.ReplicaHeartbeatRequest.FromString,
                    response_serializer=marketplace__pb2.ReplicaHeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """storage api - all replicas expose this, they're all peers
    """

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageService/Write',
            marketplace__pb2.StorageWriteRequest.SerializeToString,
            marketplace__pb2.StorageWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageService/Read',
            marketplace__pb2.StorageReadRequest.SerializeToString,
            marketplace__pb2.StorageReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageService/Search',
            marketplace__pb2.StorageSearchRequest.SerializeToString,
            marketplace__pb2.StorageSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Repair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageService/Repair',
            marketplace__pb2.RepairRequest.SerializeToString,
            marketplace__pb2.RepairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageService/SyncState',
            marketplace__pb2.SyncRequest.SerializeToString,
            marketplace__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.StorageService/CheckHealth',
            marketplace__pb2.ReplicaHeartbeatRequest.SerializeToString,
            marketplace__pb2.ReplicaHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
