apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: ebay-frontend
          image: kv-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "50051"
            - name: STORAGE_PORT
              value: "50052"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 300m

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 50051
      targetPort: 50051